[build]
  publish = "_site"
  NODE_VERSION = "14.15.3"
  # Allows overriding metadata.json via env var
  command = "[ \"$METADATA_JSON\" ] && echo $METADATA_JSON > _data/metadata.json; npm run build"
  functions = "functions/"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"
