[build]
  publish = "_site"
  # Allows overriding metadata.json via env var
  command = "[ \"$METADATA_JSON\" ] && echo $METADATA_JSON > _data/metadata.json; npm run build-ci"

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"
  for = "*.json"
    [headers.values]
      Content-Type = "application/json; charset=utf-8"
  for = "*.webmanifest"
    [headers.values]
      Content-Type = "application/json; charset=utf-8"
  for = "*.js"
    [headers.values]
      Content-Type = "application/javascript; charset=utf-8"

