backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "img/posts/all"
public_folder: "/img/posts/all"

collections:
  - label: "Blog" 
    name: "blog"
    folder: "posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Scheduled", name: "scheduled", widget: "datetime", required: false, date_format: "YYYY-MM-DD" }
      - { label: "Draft", name: "draft", required: false, widget: "boolean" }
      - { label: "Tags", name: "tags", widget: list, default: ["post"] }
      - { label: "Image", name: "image", widget: string, default: "../../img/posts/HERE" }
      - { label: "Layout", name: "layout", widget: string, default: "layouts/post.njk" }
      - { label: "Body", name: "body", widget: "markdown" }

collections:
  - label: "Short bits" 
    name: "shorts"
    folder: "short-bits"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: string, default: "layouts/post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tweet", name: "tweet", widget: "string" }
      - { label: "Short", name: "short", widget: "boolean", default: true }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Image", name: "image", widget: string, default: "../../img/short-bits/default.png" }
      - { label: "Template class", name: "templateClass", widget: "string", default: "tmpl-post" }
      - { label: "Body", name: "body", widget: "markdown" }
