# Runs build and deploy decentralized
name: Deploy to IPFS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install
    - run: npm run build
    - name: IPFS action with Pinata
      uses: aquiladev/ipfs-action@v0.1.5
      with:
        path: ./_site
        service: pinata
        pinataKey: ${{ secrets.PINATA_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET }}
        pinataPinName: piraces
